language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ardic88/docker-web -f Dockerfile.dev .

script:
  - docker run -e CI=true ardic88/docker-web npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-web"
  env: "Dockerweb-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-581956380017"
  bucket_path: "docker-web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
